### ISSUE TITLE
Add module integration to Collecting

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s-enduser#101]
At the moment there is not a specific section which explains how modules like Custom Vocab and Value Suggest integrate (that info is in the bullet points in Prompts). It might be good to have a spot at the end of the section on this module which clearly states which modules can interact with Collecting (and which don't).

**Comment by sharonmleon** [comment]
@jimsafley As far as I can tell, Custom Vocab and Numeric Data Types work with the form, but not Value Suggest?

**Comment by jimsafley** [comment]
Yes, CustomVocab and NumericDataTypes are available for the following prompt types:

- Item Property
- Item Supplementary
- User Private
- User Public

The module does not integrate with ValueSuggest.
