### ISSUE TITLE
Document "Configure Resource Page"

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s-enduser#133]
Documentation for new design flexibility for the resources pages in a site. Regions defined by theme.

**Comment by sharonmleon** [comment]
Questions and points for clarification for @jimsafley and @kimisgold 

- are there standard regions? the testing theme only has the Main region, but there are likely to be others?
- are the currently available blocks the only ones that exist, or will modules add blocks? e.g. Mapping
- is there a reason to call these chunks of content "blocks"? I'd like to call them elements, but maybe it makes sense for them to echo the page building blocks.

**Comment by sharonmleon** [comment]
Answering my own question here... the interface calls them blocks, so that's what we'll go with.

**Comment by zerocrates** [comment]
Elements of course has its own baggage in the Omeka ecosystem.

The vision here is that modules which add content to the show pages will provide a block instead in this system. I don't know if we have currently converted modules for this or not right now.

**Comment by sharonmleon** [comment]
We don't have any yet, but we probably will. Oddly mapping is the only one I can think of at the moment.

**Comment by sharonmleon** [comment]
Have gotten started on [this branch](https://github.com/omeka/omeka-s-enduser/tree/ConfigResourceBlocks). Relevant page is /sites/site_theme.md

**Comment by sharonmleon** [comment]
Oh, blocks totally makes sense. It works with the way that we're using it in page building. I originally leaned toward element as a kind of generic thing. But as John suggests, there is some ongoing association with element sets in Omeka Classic.

**Comment by allanaaa** [comment]
I'm getting some funny CSS with regions in Foundation @kimisgold. I think the images just need separate classes maybe:

http://dev.omeka.org/amayer/amayer-s/amsdev/omeka-s/s/my-omeka-s-site/item/766#lg=1&slide=0

The tiny media icon in the right sidebar is getting weird dimensions from 

> .media-list img {
  margin: 0 1rem 0 0;
  height: 5rem;
  width: auto;
}

If you uncheck the height, you see some unintended consequences with the Lightbox gallery block's fallback.

**Comment by kimisgold** [comment]
@allanaaa I've updated Foundation with some fixes, addressing the thumbnail aspect ratios and also widening coexisting left and right sidebars.

**Comment by allanaaa** [comment]
@kimisgold Thanks, that looks great! It's such a good theme for this, I decided to use it as the screenshots for the docs. Let me know what you think:
https://github.com/omeka/omeka-s-enduser/pull/146/files#diff-04f3c5412c8804db443d5f98dc0cbd8721301fa264b23fadee2ea0e7d7e78a68

**Comment by kimisgold** [comment]
I think it's a great candidate for the screenshots. The only thing at the moment is that it doesn't look like the markup for the item sets, media, and resource class are correct. Can you pull core and check? The markup should look mirror the main metadata properties and values.

**Comment by allanaaa** [comment]
Whoops, just a legacy of the earlier version of the theme, I think. Fixed now.
