### ISSUE TITLE
Proposing a hosting service for one-click installation section

### ISSUE THREAD

**Issue by Boca13** [omeka/omeka-s-enduser#172]
Hello!

I wanted to ask what steps or information I would need to provide in order to propose the addition of a hosting service to the list in this section: https://github.com/omeka/omeka-s-enduser/blob/master/docs/install.md#one-click-installation

We have created a hosting service that is based on containers and Kubernetes, with a focus on performance. Since the two branches of our business are Omeka projects and hosting, our service offers a high degree of specialization and tools for Omeka, as opposed to a hosting with a generic one-click installation system like Softaculous. Since the applications run on containers, we have images for each Omeka S version and installation is automatic. I think that our service could really help both final users and service providers. https://digitalhumanities.libnamic.com/hosting

Thank you for your consideration!

**Comment by sharonmleon** [comment]
We maintain that list based on recommendations from our users about where they have had good hosting experiences.
