### ISSUE TITLE
Update of Geonames Geographical Database

### ISSUE THREAD

**Issue by bulletuilleo** [omeka/omeka-s-enduser#194]
We are using an Omeka S version 4.0.4 instance with the Value Suggest 1.17.0 module.
The Geonames Geographical database does not update and does not include terms created in recent months. Is the problem with the Value Suggest module? 
Thanks for your help

**Comment by jimsafley** [comment]
Which vocabulary doesn't work?

- Geonames: The GeoNames geographical database
- Geonames: GeoNames features

**Comment by bulletuilleo** [comment]
Thank you for your quick answer. We are using Geonames: The GeoNames geographical database 


De: "Jim Safley" ***@***.***> 
À: "omeka/omeka-s-enduser" ***@***.***> 
Cc: "bulle leonetti" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 8 Mars 2024 15:40:03 
Objet: Re: [omeka/omeka-s-enduser] Update of Geonames Geographical Database (Issue #194) 





Which vocabulary doesn't work? 

    * Geonames: The GeoNames geographical database 
    * Geonames: GeoNames features

**Comment by jimsafley** [comment]
Are you getting no suggestions? Or are you not getting the suggestions you expect?

What are you entering to get the result you see?

**Comment by bulletuilleo** [comment]
I get a lot of suggestions using the labels or alternative labels, but I can't access any of the terms added in recent months. 
I have tried with the labels, alt labels, URL or Geonames Id. 
See for instance with this entry https://www.geonames.org/12719961/mediatheque-jacques-demy.html 


De: "Jim Safley" ***@***.***> 
À: "omeka" ***@***.***> 
Cc: "bulle leonetti" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 8 Mars 2024 16:21:50 
Objet: Re: [omeka/omeka-s-enduser] Update of Geonames Geographical Database (Issue #194) 





Are you getting no suggestions? Or are you not getting the suggestions you expect? 

What are you entering to get the result you see?

**Comment by jimsafley** [comment]
It's likely that the GeoNames API service has not been updated to include the new additions. The problem is not with the ValueSuggest module.

**Comment by bulletuilleo** [comment]
Many thanks for your answer. I shall contact them to fix it. 
Best 


De: "Jim Safley" ***@***.***> 
À: "omeka" ***@***.***> 
Cc: "bulle leonetti" ***@***.***>, "Author" ***@***.***> 
Envoyé: Vendredi 8 Mars 2024 18:12:05 
Objet: Re: [omeka/omeka-s-enduser] Update of Geonames Geographical Database (Issue #194) 





It's likely that the GeoNames API service has not been updated to include the new additions. The problem is not with the ValueSuggest module.

**Comment by allanaaa** [comment]
If a future issue arises, please make a new issue in the relevant repository for the Value Suggest module:

https://github.com/omeka-s-modules/ValueSuggest
