### ISSUE TITLE
Provide oembed page block documentation

### ISSUE THREAD

**Issue by kimisgold** [omeka/omeka-s-enduser#195]
While looking into omeka/omeka-s#2161, I realized covering oembed is one hole in our page block documentation. @allanaaa wants to be able to change the url value, but I think that it's not editable due to the information pulled from the url sitting under the advanced options. We should provide some explanation of that interaction, as well as what's intended by the refresh block option.

**Comment by allanaaa** [comment]
Is this new for 4.1? I know we have had oEmbed for media on items for a while. If so, I'll do this as part of the 4.1 pull request.

**Comment by kimisgold** [comment]
You're right, I was thinking of the oembed media having been around. The page block is indeed new and included on the [4.1 feature list](https://github.com/omeka/omeka-s/releases/tag/v4.1.0-rc).

**Comment by kimisgold** [comment]
I just found it on your [task list](https://github.com/omeka/omeka-s-enduser/issues/188) so I'll close this issue.
