### ISSUE TITLE
Need a section for the global admin?

### ISSUE THREAD

**Issue by patrickmj** [omeka/omeka-s-enduser#30]
It looks like there's a section for the admin main page, but I'm not sure if that's the global admin or, e.g., a site admin. Seems like a sharper distinction will be helpful. 

Side-note, the images aren't appearing, so it's extra hard to see what's happening.

**Comment by kimisgold** [comment]
We never make the "global" distinction in the Omeka S interface itself, and the navigation within the documentation mimics S's navigation structure. I'm hoping that is enough, but if others think we should stick "global" on that first link, that's fine.

Images should be appearing now.

**Comment by patrickmj** [comment]
I think that the fundamental roles of global admin and site admin are different enough to merit a very different approach. The idea is that the global admin is the IT person who installs and maintains it, but by design doesn't care about the content. The site admins, on the other hand, don't care about the server and maintenance (as long is it still works). They care about the content, and being able to create it.

Granted, there will be cases where those are the same person. But the general principle is, I think, to assume that they won't be.

**Comment by mebrett** [comment]
Patrick, are you suggesting a different landing page of some sort for the global admin? I've organized the user manual to echo the structure of the left hand nav itself, although I suppose the global admin things (modules, users, etc) aren't quite gathered in the [current setup](http://dev.omeka.org/docs/s/user-manual/). 

The [admin dashboard](http://dev.omeka.org/docs/s/user-manual/admin-dashboard/) page is about orienting people to what they see when they log in, not for addressing any specific user role.

**Comment by patrickmj** [comment]
I'm concerned about the differences that people will see when they log in, based on their role. I don't think that different landing pages is needed for every role, but I think a differentiation between global admin and site admin will help orient people to those high-level actions.

**Comment by mebrett** [comment]
It's not radically different (I just logged in as my author user) but I can rework the text on the page to clarify which sections are only visible to site and global admins.

**Comment by patrickmj** [comment]
Sounds good and helpful to me. Thanks.
