### ISSUE TITLE
Improve config documentation

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s-enduser#39]
We're _way_ behind on this, and I feel like have even fallen behind what was in the old wiki. Perhaps some of that is floating around on the developer side? It's annoying that this straddles the line to such a degree but we'll just have to deal with that.

**Comment by patrickmj** [comment]
A good step might be to declare an EOL on the old wiki, move content over to the appropriate place(s) in the update, and delete the old wiki, maybe just leaving links to the documentation?

**Comment by zerocrates** [comment]
Oh yeah the wiki _is_ EOL, at least to my knowledge. Nothing should be
living there.

**Comment by mebrett** [comment]
Resolved in 7486c77
