### ISSUE TITLE
404 in documentation for frontpage 

### ISSUE THREAD

**Issue by goetzk** [omeka/omeka-s-enduser#53]
Down the bottom of https://omeka.org/s/docs/user-manual/frontpage/ is "You can use the Default Site option in conjunction with the site page block "List of sites" to create a branded site index and to add an about page for the overall installation.". The text "site page" is a link which points to https://omeka.org/s/docs/sites/site_pages/#page-blocks - a 404.

**Comment by mebrett** [comment]
Fixed in ac65559
