### ISSUE TITLE
1.4 updates

### ISSUE THREAD

**Issue by zerocrates** [omeka/omeka-s-enduser#54]
* New public side "user bar" links to go directly to pages/items/sets/media on the admin side
* Asset (logo/thumbnail) upload now allows .svg and .svgz
* Changes to vocabulary import/update (added Language selection)
* New "NoThumbnail" thumbnailer (for disabling thumbnails; idea being to use for faster import, if you're going to just create them yourself some other way, or know that none of them can be thumbnailed anyway)
* Homepage setting in site admin -> Navigation (lets you pick page to load as site homepage without having to have it first in navigation, or in navigation at all)
* Configurable password requirements (this is set in local.config.php)

**Comment by mebrett** [comment]
Are the options in [Jim's comment (fairly far down)](https://github.com/omeka/omeka-s/pull/1375) the only ones for configuring the password requirements?

**Comment by jimsafley** [comment]
Yes, those are the only options.
