### ISSUE TITLE
Numeric Data Types updates

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s-enduser#78]
Existing headings: Change Search and Sort to be more in line with other documentation

Add: bulk edit documentation, including how to [convert existing properties to numeric](https://forum.omeka.org/t/order-by-identifier/11722/4?u=mebrett).

**Comment by mebrett** [comment]
Hopefully addressed decently in the branch longedits - @jimsafley could you take a look [at the new section](https://github.com/omeka/omeka-s-enduser/blob/longedits/docs/modules/numericdatatypes.md#bulk-edit-numeric-data) when you have a chance and let me know if I got anything wrong?

**Comment by jimsafley** [comment]
It looks 👌

**Comment by mebrett** [comment]
Resolved in #84

**Comment by zerocrates** [comment]
Oops, I thought there was already an issue for this and looked but clearly did not _see_
