### ISSUE TITLE
Review draft docs for 3

### ISSUE THREAD

**Issue by mebrett** [omeka/omeka-s-enduser#82]
Review the docs on branch `3alpha` against an installation running Omeka S 3 to make sure we haven't missed anything.

Things to look for: 
- Sites tab when adding/editing an Item
- New interface for the Items tab of the site resources
- consolidation of site admin and settings tabs, with new documentation section for that. 
- new language option in global settings

@zerocrates @kimisgold did I miss anything?

**Comment by kimisgold** [comment]
Just a couple things: 

* New "Advanced" tab within item/edit: replaces "thumbnail" tab and includes item owner setting.
* Values now sortable within the resource form

**Comment by zerocrates** [comment]
Just added: resource templates let you pick multiple data types for a property now: if you pick more than one type users get to choose between them in the resource form when using that property.
