### ISSUE TITLE
Update documentation for Fedora Connector Module

### ISSUE THREAD

**Issue by sharonmleon** [omeka/omeka-s-enduser#89]

**Comment by georgiawebgurl** [comment]
I'm tackling this now and it will follow a similar look/feel as the recently updated Dspace Connector format.

**Comment by sharonmleon** [comment]
@matthewjmckinley You made the basic adjustments when you released the module in February. Do we need anything else here or can we close this?

**Comment by matthewjmckinley** [comment]
Added documentation and new image for 'Ignore parent container' and 'Import direct descendent only'
